core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('store.urls', namespace='store')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path


#import views
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.HomeView.as_view(), name='homepage'),
    path('product/<slug>/', views.ItemDetailsView.as_view(), name='productpage'),
    path('order-summary/', views.OrderSummary.as_view(), name='order-summary'),
    path('checkout/', views.CheckoutView.as_view(), name='checkoutpage'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='cartview'),
    path('add-item-to-cart/<slug>/', views.add_item_to_cart, name='additemview'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='removeview'),
    path('remove-item-from-cart/<slug>/',
         views.remove_single_item_from_cart, name='removeitemview'),
    path('payment/<payment_option>/', views.PaymentView.as_view(),name='payment'),
    path('add-coupon/', views.add_coupon,name='coupon'),
]

store/models.py
from django.db import models
from django.conf import settings
from django_countries.fields import CountryField

from django.shortcuts import reverse
from django.contrib.auth.models import User

# Create your models here.
# orderitem

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('OW', 'Out Wear'),
    ('SW', 'Sports Wear'),
)

LABEL_CHOICES = (
    ('p', 'primary'),
    ('s', 'secondary'),
    ('d', ' danger'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(
        default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa sint voluptatibus! Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.')
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=1)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    image = models.ImageField(blank=True, null=True)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("store:productpage", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("store:cartview", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("store:removeview", kwargs={"slug": self.slug})

    @property
    def get_discount(self):
        product_price = self.price - self.discount_price
        rounded_price = round(product_price, 2)
        return rounded_price

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url 


class OrderItem(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        if self.item.discount_price:
            return self.quantity * self.item.get_discount
        else:
            return self.quantity * self.item.price

    def get_amount_saved(self):
        if self.item.discount_price:
            return self.quantity * self.item.discount_price


# order


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    billing_address = models.ForeignKey('BillingAddress',blank=True, null=True, on_delete=models.SET_NULL)
    payment = models.ForeignKey('Payment', blank=True,null=True,on_delete=models.SET_NULL)
    coupon = models.ForeignKey('Coupon', blank=True,null=True,on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.user.username}  '

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        total -= self.coupon.amount
        return total

class BillingAddress (models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    appartmentent_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.email
class  Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True, null=True, on_delete=models.SET_NULL)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email

class Coupon (models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()
    def __str__(self):
        return self.code

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4 my-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fa fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home-page.html
{% extends 'base.html' %}{% load static %}{% block content%}
<!--Carousel Wrapper-->
<div
  id="carousel-example-1z"
  class="carousel slide carousel-fade pt-4"
  data-ride="carousel"
>
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li
      data-target="#carousel-example-1z"
      data-slide-to="0"
      class="active"
    ></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <!--First slide-->
    <div class="carousel-item active">
      <div
        class="view"
        style="
          background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg');
          background-repeat: no-repeat;
          background-size: cover;
        "
      >
        <!-- Mask & flexbox options-->
        <div
          class="mask rgba-black-strong d-flex justify-content-center align-items-center"
        >
          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Drip Lord</strong>
            </h1>

            <p>
              <strong>We put fabric in stiches</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong
                >The most comprehensive tutorial for the Bootstrap 4. Loved by
                over 500 000 users. Video and written versions available. Create
                your own, stunning website.</strong
              >
            </p>

            <a
              
              class="btn btn-outline-white btn-lg"
              >Start Shopping
              <i class="fas fa-shopping-cart"></i>
            </a>
          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
      </div>
    </div>
    <!--/First slide-->

  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a
    class="carousel-control-prev"
    href="#carousel-example-1z"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#carousel-example-1z"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container">
    <!--Navbar-->
    <nav
      class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5"
    >
      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#basicExampleNav"
        aria-controls="basicExampleNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>
        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input
              class="form-control mr-sm-2"
              type="text"
              placeholder="Search"
              aria-label="Search"
            />
          </div>
        </form>
      </div>
      <!-- Collapsible content -->
    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">
      <!--Grid row-->
      <div class="row wow fadeIn">
        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <!--Card-->
          <div class="card">
            <!--Card image-->
            <div class="view overlay">
              <img
                src="{{ item.imageURL }}"
                class="card-img-top"
                alt=""
              />
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{item.get_category_display}}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{item.get_absolute_url }}" class="dark-grey-text"
                    >{{item.title}}
                    <span
                      class="badge badge-pill {{ item.get_label_display }}-color"
                      >NEW</span
                    >
                  </a>
                </strong>
              </h5>
              {% if item.discount_price %}
              <h4 class="font-weight-bold blue-text">
                <span class="mr-1">
                  <del> {{ item.price }} </del>
                </span>
                <strong> {{ item.get_discount }} </strong>
              </h4>
              {% else %}
              <h4 class="font-weight-bold blue-text">
                <strong> {{ item.price }} </strong>
              </h4>
              {% endif %}
            </div>
            <!--Card content-->
          </div>
          <!--Card-->
        </div>
        {% endfor %}
      </div>
      <!--Grid row-->
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">
        <!--Arrow left-->
        {% if page_obj.has_previous %}
        <li class="page-item disabled">
          <a class="page-link" href="?page={{pag_obj.previous_page_number}}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif%}

        <li class="page-item active">
          <a class="page-link" href="?page={{pag_obj.number}}"
            >{{pag_obj.number}}
            <span class="sr-only">(current)</span>
          </a>
        </li>
       
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{pag_obj.next_page_number}}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {%endif %}
      </ul>
    </nav>
    {% endif %}
    <!--Pagination-->
  </div>
</main>
<!--Main layout-->
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" >{% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/items_list.html
html
{% block content %}
    {% for item in items %}
        {{item.title}}
    {% endfor %}
{% endblock %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar ">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'store:homepage'%}">
        <strong class="blue-text">Milano Store</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'store:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ cart_items }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_snippet.html
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    
    <form class="card p-2" action="{% url 'store:coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% comment %}{% if DISPLAY_COUPON_FORM %}{% endif %}{% endcomment %}

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'store:removeitemview' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'store:additemview' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'store:removeview' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href="{% url 'store:checkoutpage' %}">Proceed to checkout</a>
            <a class='btn btn-primary float-right' href="{% url 'store:homepage' %}">Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/product-page.html
{% extends 'base.html' %}{% load static %} {% block content %}

<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <img
          src="{{ item.imageURL }}"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">
        <!--Content-->
        <div class="p-4">
          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1"
                >{{item.get_category_display}}</span
              >
            </a>
          </div>

          {% if item.discount_price %}
          <p class="lead">
            <span class="mr-1">
              <del> {{ item.price }} </del>
            </span>
            <span>{{item.get_discount}}</span>
          </p>
          {% else %}
          <p class="lead">
            <span class="mr-1">
              <del> </del>
            </span>
            <span>{{item.price}}</span>
          </p>
          {% endif %}

          <p class="lead font-weight-bold">Description</p>

          <p>{{ item.description }}</p>

          <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input
              type="number"
              value="1"
              aria-label="Search"
              class="form-control"
              style="width: 100px"
            />
            <a
              href="{{ item.get_add_to_cart_url }}"
              class="btn btn-primary btn-md my-0 p"
            >
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
          </form>
          <a
            href="{{ item.get_remove_from_cart_url }}"
            class="btn btn-danger btn-md my-0 mt-2 p"
          >
            Remove from cart
          </a>
        </div>
        <!--Content-->
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <hr />

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">
      <!--Grid column-->
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">Additional information</h4>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus
          suscipit modi sapiente illo soluta odit voluptates, quibusdam officia.
          Neque quibusdam quas a quis porro? Molestias illo neque eum in
          laborum.
        </p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">
      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">
        <img
          src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
          class="img-fluid"
          alt=""
        />
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}